on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm run build
          who-to-greet: 'Mona the Octocat'
      - name: Test
        run: npm run test